[package]
name = "trade_fa_coin_example"
version = "1.0.0"
authors = []

[addresses]
TradeFACoin = "_"
FACoin = "0xd372f2741ce4043822c13619e4fbda69c20c80692f78774a294fa1aebab3c054"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.fa_coin_example]
git = "https://github.com/HynDuf/aptos_move_examples"
rev = "testnet"
subdir = "fa_example"

[dev-dependencies]
